#!/bin/bash

gnome-terminal -e "./routedLS A logA.txt PA3_initialization.txt" -t "Router A"&
gnome-terminal -e "./routedLS B logB.txt PA3_initialization.txt" -t "Router B"&
gnome-terminal -e "./routedLS C logC.txt PA3_initialization.txt" -t "Router C"&
gnome-terminal -e "./routedLS D logD.txt PA3_initialization.txt" -t "Router D"&
gnome-terminal -e "./routedLS E logE.txt PA3_initialization.txt" -t "Router E"&
gnome-terminal -e "./routedLS F logF.txt PA3_initialization.txt" -t "Router F"&
